language: go
go:
- tip
before_install:
- gem install fpm
- gem install package_cloud
- sudo apt-get install -y rpm
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
before_script:
- wget https://raw.githubusercontent.com/mvertes/txt2man/master/txt2man -O txt2man
- chmod +x ./txt2man
- export PATH=$PATH:$PWD
script:
- $HOME/gopath/bin/goveralls -service=travis-ci
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make
  deploy-docs
deploy:
  provider: script
  script: make deploy-packages
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: oNmSylz2QfFRsgZNPXQMUF3PouJb7sQZigDC9cKZRytLA0arMUQyPhuMoJ0EE+toz8TYh7Fw+pAafIoCbxpvsbcUXgw4ZT6/swrz1cVH8xL2wEEwYktL3rX1D4IbMvq1ew09Gsnfe9XnKBPv6JUjOrdP2zUqLXpRbGsRsM13gDXbtee9x0v0iib5zP0RxMHvmyM0oES8IloC1l2IAqkVIJ1ub0/0ocNsCgYrv7ppVFQ/fqu+i77x2YGOhOuQqTRMyNC5RbOjI2GS3xNzXs7Wj23YoYz3G54VwAustV7s5V5Lt8m5nRkq1x7sfd/DMeB7Rik1b7af3Fr22RNLMxyUiaq3EQPQQFiDKFb7ds6MGuKP39feetSlqYxb2R7x2PExDKSBLPrHHwH/RxlC6UnYnGP8HDybjGB3pfjI7I7jSgwNddn29Tz34gSLWOCc+lNXVqwqQK7U8ylNC1FNnLtZIsZpXVPjZy4saNBKpIjnT8+LZgvBYTPIFpOtpkSMDv0lejvey0FvAIUqkJb6/ENighyl8+y/FbxHTXn12Yc6Fxpxty/hJVjJiMmC5CudaFxujfgjO4lZZRDC71Y+U3aXGot0Jq7NuVmoSAXAUhYPecnzgNw62WHiTxwIejjJcTN6sGQLef56gU0BcXQUmUpJHf2wu0KIHEiV4Q6HWbrXCGs=
  - secure: q4s2fTGdzcIcbcCVCsPXVBNpl+o+yQVNu4F+kSBYZOjd+cGpBraBtBT/b4yAAnFodmF2qv14cEfSWT8deDkKCRaOcfoDfHqDMn4hPZxHxU0cgwtJpJI6kgnj1JaQ/10k5RKIYL0KDxbi2phaegj804UpUGn7D7lyvlYlysrj3PvZL2tHlCdTcGb8HmBS6aCtfiEKdl50IpEnAolMnsOGBshX6cFWGTfdekyKTl71kJ2gWB8z/HdCSENQlbexzHp/HHN13uiiEdM7Hjoin1/VfPzAk7+cYrzIsdB08kgSC0j50MF7V2yntOwaXfMR9dyrjlbulpUbJhHz4OQ6Bk7Ui3Xil646SNdZpaW2LwrzPGPnAc6Rjje7EXU6h4soBHh/aFtkbHciXzsxG60dd4lZ7v/fuah/j1wmutYSxW5V+2gEywsducf+GexbX+dxb2oYsf72Q6qGEwZ5YdkEp8CI2WmcG0Ks3KM3Y4FgBfKqtKIAujW1KMmrSfA0Uzlz3m+DcE+hW/2D2pjOuIShS2DjekyjxZRwPhlMqKgkJa5ZnVEWquUFAjWfzABdKv54KCf2LS15cAMwMMXzUvOa/VGMmQ123f9cXyY5qOe70R2ID5XJUwL+YlZzDyudioNSlAcL9ELPAwaTSwYZxNvDgpMg4PrK9WihCLW/RPiEsNCvRsE=
